- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello World"
    - name: Create Directory
      file:
        path: /tmp/playbookTest
        state: directory
        mode: "0755"
