- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello World"
    - name: Create Directory
      file:
        path: /playbookTest
        state: directory
        owner: root
        group: root
        mode: "0755"
