- name: AWX Test
  hosts: ansible_server

  tasks:
    - name: ファイル作成
      file:
        path: /tmp/ansible_test_file.txt
        state: touch

    - name: ファイルに内容記述
      lineinfile:
        path: /tmp/ansible_test_file.txt
        line: "こんにちは！"
