- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello World"
    - name: Create Directory
        path: /playbookTest
        state: directory
        mode: "0755"
