---
- name: Execute curl to create VM on Proxmox
  hosts: localhost
  tasks:
    - name: Execute curl command to create VM
      ansible.builtin.shell: |
        curl -k -X POST '{{ proxmox_url }}/api2/json/nodes/{{ node }}/qemu' \
             -H 'Authorization: PVEAPIToken={{ token_name }}={{ token_secret }}' \
             -d vmid={{ vmid }} \
             -d name={{ vm_name }} \
             -d cores={{ cores }} \
             -d memory={{ memory }} \
             -d cdrom={{ cdrom_path }} \
             -d ostype={{ ostype }}
      args:
        executable: /bin/bash

