---
- name: Create a new VM on Proxmox
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a new VM via API
      uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/qemu"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        body:
          vmid: "{{ vmid }}"
          name: "{{ vm_name }}"
          cores: "{{ vm_cores }}"
          memory: "{{ vm_memory }}"
          disk: "{{ vm_disk_size }}"
          storage: "{{ proxmox_storage }}"
          ostype: "l26"
          iso: "{{ proxmox_iso }}"
          net0: "model=virtio,bridge=vmbr0"
        body_format: json
        status_code: 200, 400
      register: vm_creation_result

    - name: Debug VM creation result
      debug:
        var: vm_creation_result.json

